version: '3.9'

services:
  db:
    image: postgres:15
    container_name: my_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    container_name: my_nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  db_data:
